"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[░▒▓](fg:#b16286)\
$hostname\
[](fg:#b16286 bg:#458588)\
$directory\
[](fg:#458588 bg:#98971a)\
$git_branch$git_status\
[](fg:#98971a bg:#689d6a)\
$nodejs\
[](fg:#689d6a bg:#8f3f71)\
$conda\
[](fg:#8f3f71 bg:#d79921)\
${custom.python}\
[](fg:#d79921 bg:#cc241d)\
$docker_context\
[](fg:#cc241d bg:#d65d0e)\
$kubernetes\
[](fg:#d65d0e)\
$fill\
$time\
$line_break\
${env_var.STARSHIP_RANDOM_ARROW}"""

[character]
success_symbol = '[╰─❯](bold fg:#a6e3a1)'
error_symbol = '[╰─❯](bold fg:#f38ba8)'

[fill]
symbol = '·'
style = 'fg:#45475a'

[hostname]
ssh_only = false
ssh_symbol = '@'
style = "fg:#ffffff bg:#b16286"
format = '[ $ssh_symbol$hostname ]($style)'

[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false
style = "fg:#ffffff bg:#458588"
format = '[  $path ]($style)'

[git_branch]
symbol = ' '
style = "fg:#ffffff bg:#98971a"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "fg:#ffffff bg:#98971a"
format = '[ $all_status$ahead_behind]($style)'

[nodejs]
symbol = '⬢ '
style = "fg:#ffffff bg:#689d6a"
format = '[ $symbol$version ]($style)'

[custom.python]
command = "python3 --version | awk '{print $2}'"
when = "true"
symbol = '🐍 '
style = "fg:#ffffff bg:#d79921"
format = '[ $symbol$output ]($style)'

[docker_context]
symbol = '🐳 '
style = "fg:#ffffff bg:#cc241d"
format = '[ $symbol$context ]($style)'

[kubernetes]
symbol = '☸ '
style = "fg:#ffffff bg:#d65d0e"
format = '[ $symbol$context ]($style)'

[time]
disabled = false
time_format = '%I:%M:%S %p'
style = "bold fg:#689d6a"
format = '[  $time ]($style)'

[custom.random_arrow]
command = "bash -c 'colors=(42 198 214 39 177 85 226 207 141 122); printf \"\x1b[1;38;5;%sm╰─❯\x1b[0m\" \"${colors[$RANDOM % 10]}\"'"
when = "true"
format = "$output "

[env_var.STARSHIP_RANDOM_ARROW]
variable = "STARSHIP_RANDOM_ARROW"
default = "╰─❯"
format = "$env_value "

[conda]
symbol = '🅒 '
style = "fg:#ffffff bg:#8f3f71"
format = '[ $symbol$environment ]($style)'
ignore_base = false
